config/routes.rb
Rails.application.routes.draw do
  
  devise_for :clientes
  devise_for :admins
  resources :contacts
  resources :orders
  resources :products
  resources :menu
  root 'home#index'

  get 'add_item/:id', to: 'orders#add_item', as: 'add_item'
  get 'close_order/:id', to: 'orders#close_order', as: 'close'
  get 'reservation', to: 'contacts#reservation', as: 'reserv'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cliente.rb
class Cliente < ApplicationRecord
  has_many :orders
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_products
    has_many :products, through: :order_products
    belongs_to :cliente

    enum status: [:active, :archieve]

    accepts_nested_attributes_for :order_products, reject_if: :all_blank, allow_destroy: true
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
    belongs_to :order, :optional => true
    belongs_to :product, :optional => true
end

app/models/order_products.rb
class OrderProducts < ApplicationRecord
    belongs_to :order
    belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :order_products
    has_many :orders, through: :order_products
    monetize :price_cents
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:cpf])
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    def index
    end

    def reservation
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :orders, only: %i[index]

  def index; end

  private

  def orders
    @orders ||= Order.all
  end
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
    def index
        @products = Product.all
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :order, only: %i[show edit update destroy]

  def index
    orders
  end

  def show; end

  def new
    order
    order.order_products.build
  end

  def add_item
    @client = Cliente.find(id)
  end

  def close_order
    order
    order.status = 1
    order.save
    redirect_to order
  end

  def edit
    order
  end

  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if order.update(order_params)
        format.html { redirect_to order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: order }
      else
        format.html { render :edit }
        format.json { render json: order.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def orders
    @orders ||= Order.all
  end

  def order
    @order ||= id.present? ? Order.find(id) : Order.new
  end

  def id
    @id ||= params[:id]
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def order_params
    # TODO: Refatorar
    params.require(:order).permit(:status, :cliente_id, order_products_attributes: %i[id product_id quantity])  
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy]

  def index
    @products = Product.all
  end

  def show
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/clientes/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/clientes/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Acessar", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Cadastrar", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Esqueceu sua senha?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/contacts/index.html.erb
<h1 class="h1-new">Contato</h1>
<form class="form-content minium">
    
    <div class="field">
        <label>Nome: </label>
        <input type="text">
    </div>

    <div class="field">
        <label>Email: </label>
        <input type="email">
    </div>

    <div class="field">
        <label>Telefone: </label>
        <input type="email">
    </div>
    
    <div class="field">
        <label>Mensagem: </label>
        <textarea rows="7" cols="30"> </textarea>
    </div>
    
        <%= link_to 'Enviar', '#', class: 'btn'%>
        <%= link_to 'Voltar', root_path, class: 'btn'%>
</form>

app/views/contacts/reservation.html.erb
<h1 class="h1-new">Formulário de reserva</h1>
<form class="form-content minium">
    <div class=field>
        <label>Nome: </label>
        <input type="text">
    </div>
    <div class=field>
        <label>Email: </label>
        <input type="email">
    </div>
    <div class=field>
        <label>Telefone: </label>
        <input type="email">
    </div>
    <div class=field>
        <label>Data pretendida:</label>
        <input type="text">
    </div>
    <br>
    <div class=field>
    <label>Mensagem: </label>
    <textarea rows="7" cols="30"> </textarea>
    </div>
        <%= link_to 'Enviar', '#', class: 'btn'%>
        <%= link_to 'Voltar', root_path, class: 'btn'%>
</form>

app/views/home/index.html.erb
<header class="top-header">
    <h1> DelaBella Projetc </h1>
    <nav class="top-nav">
        <ul>
            <li><%= link_to 'Cardápio', menu_index_path %></li>
            <%unless admin_signed_in? %>
                <li><%= link_to 'Contato', contacts_path %></li>
            <%end%>
                <% if cliente_signed_in? %>
                    <li><%= link_to 'Comanda', add_item_path(current_cliente) %></li>  
                    <li><%= link_to 'Histórico', '#' %></li>  
                    <li><%= link_to 'Sair', destroy_cliente_session_path, method: :delete %></li>
                    
                <%elsif admin_signed_in?%>
                    <li><%= link_to 'Abrir comanda', new_order_path %></li>
                    <li><%= link_to 'Comandas', orders_path %></li>
                    <li><%= link_to 'Produtos', products_path %></li>
                    <li><%= link_to 'Sair', destroy_admin_session_path, method: :delete %></li>
                <%else%>
                    <li><%= link_to 'Login', new_cliente_session_path %></li>
                <%end%>
        </ul>
    </nav>
    <% if cliente_signed_in? %>
        <h1>Seja bem-vindo <u><%= current_cliente.email %></u></h1>
    <%end%>
</header>    
<main class="main">
    <section class="top-main">
        <h2> Suas sextas e sábados nunca mais serão os mesmas </h2>
    </section>
    <section class="icons-content">
        <article class="art-icon">
            <%= image_tag '4.png', class: 'icon-img' %>
            <h3 class="icon-text">Snooker bar</h3>
        </article>
        <article class="art-icon">
            <%= image_tag '2.png', class: 'icon-img' %>
            <h3 class="icon-text">Música ambiente</h3>
        </article>
        <article class="art-icon">
            <%= image_tag '1.png', class: 'icon-img' %>
            <h3 class="icon-text">Mesas de poker</h3>
        </article>
        <article class="art-icon">
            <%= image_tag '5.png', class: 'icon-img' %>
            <h3 class="icon-text">Eventos corporativos</h3>
        </article>
        <article class="art-icon">
            <%= image_tag '3.png', class: 'icon-img' %>
            <h3 class="icon-text">E aquela cerveja gelada!</h3>
        </article>
        <article class="art-icon">
            <%= image_tag '6.jpeg', class: 'icon-img' %>
            <h3 class="icon-text">!</h3>
        </article>
    </section>
</main>
<section class="middle-bot-content">
    <h2>Comemore sua festa conosco!</h2>
    <%= link_to 'Reserve aqui!', reserv_path ,class: 'btn' %>
</section>

<footer class="footer-content">
    <p> Copyright &copy <%= Date.current.year %> </P>
</footer>

app/views/layouts/application.html.erb
<meta name="viewport" content="width=device-width">
<meta charset="utf-8">
<!DOCTYPE html>
<html>
  <head>
    <title>DelabellaProjectReleased</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Laila" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<body>
    <%= yield %>
</body>
</html>

app/views/menu/index.html.erb
<h1 class="h1-new">Menu</h1>
<form class="form-content">
  <div class='row-title'>
    <label class='col-1 col-title'>Produto</label>
    <label class='col-2 col-title'>Preço</label>
  </div>

  
    <% @products.each do |product| %>
        <div class='row'>
          <label class='col-1'><%= product.name %></label>
          <label class='col-2'><%= humanized_money_with_symbol(product.price) %></label>
        </div>
    <% end %>
  
<br>
<%= link_to 'Página Principal', root_path, class: "btn" %>
</form>

app/views/orders/_form.html.erb
<div class="form-content minium">
<%= form_for(order) do |f| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :cliente_id, 'Cliente' %>
    <%= f.select("cliente_id", Cliente.all.collect {|c| [ c.cpf, c.id ] }, { include_blank: true }, autofocus: true)%>
  </div>
  
  <div class="field">
    <%= f.fields_for :order_products do |o| %>
        <%= render partial: "order_products_fields", locals: { f: o} %>
    <% end %>

    <div class="field">
      <%= link_to_add_association('[Adicionar Produto]', f, :order_products, partial: 'order_products_fields') %><br/>
    </div>
  </div>
  
  <div class="actions">
    <%= f.submit 'Gerar Comanda' %>
  </div>
<% end %>
<%unless cliente_signed_in?%>
  <%= link_to 'Voltar', orders_path, class: 'btn' %>
<%else%>
  <%= link_to 'Voltar', add_item_path(current_cliente), class: 'btn'%>
<%end%>
</div>

app/views/orders/_order_products_fields.html.erb
<div class="nested-fields">
    <div class="field">
        <%= f.label :product_id, 'Produto' %>
        <%= f.select("product_id", Product.all.collect {|p| [ p.name, p.id ] }, { include_blank: true }, autofocus: true)%>
        <%= f.label :quantity, 'Quantidade' %>
        <%= f.number_field :quantity %>
        <br>
        <%= link_to_remove_association('Remover', f) %>
        <hr>
    </div>
</div>

app/views/orders/add_item.html.erb
<h1 class="h1-new">Pedidos</h1>
<form class="form-content">
    <% @client.orders.each do |o| %>
      <%if o.status == 'active' %>
        <% x = (o.id + 2) * 2 %>
        <%= "Número da comanda #{x}" %><%= Date.current.month%><%= Date.current.day%>
        <br> 
        <%= "Produtos: #{o.products.pluck(:name).to_s}" %>
        <br>
        <br>
        <%= link_to 'Adicionar produto', edit_order_path(o), class: 'btn'%>
        <%= link_to 'Finalizar', '#', class: 'btn'%>
        <br>
        <br>
        <hr>
      <%end%>
    <%end%>
    <br>
    <%= link_to 'Página Principal', root_path, class: 'btn' %>
</form>

app/views/orders/edit.html.erb
<h1 class="h1-new">Fazer Pedido</h1>
<%= render 'form', order: @order %>

app/views/orders/index.html.erb
<h1 class="h1-new">Pedidos</h1>
<form class="form-content">
<table>
  <thead>
    <tr>
      <th class="th-index">Status</th>
      <th class="th-index space-c">Produto</th>
      <th class="th-index space-c">Cliente</th>
      <th colspan="10"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.status_i18n %></td>
        <td class="space"><%= order.products.pluck(:name).to_sentence %></td>
        <td><%= link_to 'Editar', edit_order_path(order) %></td>
        <td><%= link_to 'Encerrar', order %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Pedido', new_order_path, class:'btn' %>
<%= link_to 'Página Principal ', root_path, class:'btn' %>

</form>

app/views/orders/new.html.erb
<h1 class="h1-new">Novo Pedido</h1>

<%= render 'form', order: @order %>

app/views/orders/show.html.erb
<form class="form-content show">
  <p>
    <strong>Status:</strong>
    <%= @order.status_i18n %>
  </p>

  <% @order.order_products.each do |o| %>
    <% o.quantity.to_i %>
  <% end %>
  <p>
  <% z = 0 %>
  <strong>Produtos na comanda:</strong>
    <br>
    <br>
    <% @order.order_products.each do |p| %>
      <% x = p.quantity %>
      <%= p.quantity %>x 
      <%= p.product.name %>
      <%= "---- #{humanized_money_with_symbol(p.product.price)} un" %>
      <% y = p.product.price %>
      <% z = z + (x*y) %>
      <hr>
    <% end %>
    <br> 
    <br>
    <%= "Total: R$ #{z}" %>
  </p>


  <%unless cliente_signed_in?%>
    <br>
    <br>
    <br>
    <%= link_to 'Encerrar', close_path(@order), class: 'btn' %>
    <%= link_to 'Editar pedido', edit_order_path(@order), class:'btn' %>
    <%= link_to 'Voltar', orders_path, class: 'btn' %>
  <%else%>
    <%= link_to 'Editar pedido', edit_order_path(@order), class:'btn' %>
    <%= link_to 'Voltar', add_item_path(current_cliente), class: 'btn'%>
  <%end%>
</form>

app/views/products/_form.html.erb
<div class="form-content minium">
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, 'Produto'%>
    <%= f.text_field :name, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :price, 'Preço R$' %>
    <%= f.text_field :price %>
  </div>

  <div class='actions'>
    <%= f.submit 'Cadast. Produto' %>
  </div>
    <%= link_to 'Voltar', products_path, class: 'btn' %>
  <% end %>
</div>

app/views/products/edit.html.erb
<h1 class="h1-new">Atualizar Produto</h1>
<%= render 'form', product: @product %>

app/views/products/index.html.erb
<h1 class="h1-new">Produtos</h1>
<form class="form-content">
<table>
  <thead>
    <tr>
      <th class="th-index space">Nome</th>
      <th class="th-index">Preço</th>
      <th colspan="10" class="space"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
          <td class="space"><%= product.name %></td>
          <td><%= humanized_money_with_symbol(product.price) %></td>
            <td class="space-b"><%= link_to 'Show', product %></td>
            <td><%= link_to 'Edit', edit_product_path(product) %></td>        
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'Novo Produto', new_product_path, class: "btn" %>
<%= link_to 'Página Principal', root_path, class: "btn" %>
</form>

app/views/products/new.html.erb
<h1 class="h1-new">Cadastro de produtos</h1>
<%= render 'form', product: @product %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<form class="form-content show minium">
  <p>
    <strong>Produto:</strong>
    <%= @product.name %>
  </p>
    <strong>Preço:</strong>
    <%= humanized_money_with_symbol(@product.price) %>
  </p>

  <%= link_to 'Editar', edit_product_path(@product), class: "btn" %>
  <%= link_to 'Voltar', products_path, class: "btn" %>
</form>